---
server:
  port: 8086

management:
  endpoints:
    web:
      base-path: /

logging.level.com.julien.search: debug

http:
  pool:
    poolSize: 50
    getConnectionTimeout: 5000
    readTimeout: 100000

database:
  login:
    url: ${DATABASE_URL}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    #enableUserValidation: false

youtube:
  api-key: ${YOUTUBE_APIKEY}
  maxResults: 5

youtube-dl:
  location: /usr/local/bin/yt-dlp

downloads:
  location: /Users/zer0x/Desktop

history:
  enabled: true
  filename: output.txt
  #location: /home/zer0x/Desktop

